# MySQL、Redis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
#日志
logging:
  level:
    root: info
    com.study.demo: debug

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

ignore:
  urls:
    - /admin/login            #登录接口
    - /admin/noauth           #白名单接口
    - /swagger-resources      #后面都是swagger文档
    - /v2/api-docs
    - /v2/api-docs-ext
    - /doc.html
    - /webjars/**
server:
  port: 9000
